### ISSUE TITLE
ESP32-S3 support?

### ISSUE THREAD

**Issue by krystof-k** [n-serrette/esphome_sd_card#15]
Hey there, I can't make it work for ESP32-S3 (using AI-S3 board). I get `Failed to mount card` no matter the pins I use.

This is my current config:

```yaml
external_components:
  source: github://n-serrette/esphome_sd_card

sd_mmc_card:
  id: card
  mode_1bit: true
  clk_pin: GPIO36
  cmd_pin: GPIO35
  data0_pin: GPIO37
  # data1_pin: GPIO4
  # data2_pin: GPIO12
  # data3_pin: GPIO13

sd_file_server:
  id: file_server
  url_prefix: file
  root_path: "/"
  enable_deletion: true
  enable_download: true
  enable_upload: true
```

I have [this SD card reader](https://www.laskakit.cz/en/sd-card-modul-spi/), CS is connected to GPIO1. When using ESP32 (WT32-ETH01) it worked fine.

But the result is this:

```
[11:16:35][C][sd_mmc_card:020]: SD MMC Component
[11:16:35][C][sd_mmc_card:021]:   Mode 1 bit: TRUE
[11:16:35][C][sd_mmc_card:022]:   CLK Pin: 36
[11:16:35][C][sd_mmc_card:023]:   CMD Pin: 35
[11:16:35][C][sd_mmc_card:024]:   DATA0 Pin: 37
[11:16:35][E][sd_mmc_card:044]: Setup failed : Failed to mount card
[11:16:35][E][component:082]:   Component sd_mmc_card is marked FAILED
```

Any idea how to do it?

**Comment by youkorr** [comment]
you are missing data3

**Comment by krystof-k** [comment]
Could you be more specific, please? I'm using SPI mode, if I add `data3_pin`, it doesn't havy any effect:

https://github.com/n-serrette/esphome_sd_card/blob/f4a5bb8eacdb1bda0ad777694c23f28048479031/components/sd_mmc_card/sd_mmc_card_esp32_arduino.cpp#L17

**Comment by youkorr** [comment]
![Image](https://github.com/user-attachments/assets/b73f039b-288f-4f6a-9c4e-3dbebc826baf)

**Comment by youkorr** [comment]
does it work??

**Comment by krystof-k** [comment]
I will retry that again later, but based on the code adding the `data3_pin` doesn't have any effeect in 1-bit mode. However I just found out that I probably need to [add a 10k pullup](https://github.com/espressif/arduino-esp32/tree/master/libraries/SD_MMC#pin-assignments-for-esp32-s3) to the CS pin.

**Comment by krystof-k** [comment]
Unfortunately no, it's not working. I tried this:

```yaml
sd_mmc_card:
  id: card
  mode_1bit: true
  clk_pin: GPIO36
  cmd_pin: GPIO35
  data0_pin: GPIO37
  data3_pin: GPIO38
```

And adding pull-ups to all CS, MOSI,SCK and MISO, but it still shows the same `Failed to mount card` error.

**Comment by youkorr** [comment]
Is the card reader properly powered?

**Comment by krystof-k** [comment]
I can't make it work. It works only with ESP32-CAM. Any board I use and connect any SD card reader, I get either `Failed to set pins` or `Failed to mount card`. I really have no idea what am I doing wrong or where is the problem.

**Comment by youkorr** [comment]
you have a pin error it's not the right pin

**Comment by krystof-k** [comment]
I have tried everything. I have brand new [microSD reader module](https://www.laskakit.cz/en/laskakit-microsd-card-modul/), connected like this:

```
black GND → GND
red VCC → 3V3
blue SDO (DATA0) → GPIO2
yellow SCK (CLK) → GPIO14
white SDI (CMD) → GPIO15
```

CS (DATA3) pin has 3V on the module, as I measured and verified.

This is the config:

```yaml
external_components:
  source: github://n-serrette/esphome_sd_card

sd_mmc_card:
  id: storage
  mode_1bit: true
  clk_pin: GPIO14
  cmd_pin: GPIO15
  data0_pin: GPIO2
```

I tried both ESP32 and ESP32-S3 boards and I always get `Failed to mount card`.

Exactly the same config on ESP32-CAM works:

```
[18:07:38][C][sd_file_server:016]: SD File Server:
[18:07:38][C][sd_file_server:017]:   Address: cam.local:80
[18:07:38][C][sd_file_server:018]:   Url Prefix: file
[18:07:38][C][sd_file_server:019]:   Root Path: /
[18:07:38][C][sd_file_server:020]:   Deletation Enabled: TRUE
[18:07:38][C][sd_file_server:021]:   Download Enabled : TRUE
[18:07:38][C][sd_file_server:022]:   Upload Enabled : TRUE
[18:07:38][C][sd_mmc_card:020]: SD MMC Component
[18:07:38][C][sd_mmc_card:021]:   Mode 1 bit: TRUE
[18:07:38][C][sd_mmc_card:022]:   CLK Pin: 14
[18:07:38][C][sd_mmc_card:023]:   CMD Pin: 15
[18:07:38][C][sd_mmc_card:024]:   DATA0 Pin: 2
```
