### ISSUE TITLE
GPIO expanders do not appear to work for CS pin

### ISSUE THREAD

**Issue by cryptk** [n-serrette/esphome_sd_card#20]
It does not appear that this component allows for GPIO expanders to be used for the various pins.  While this is likely a poor design choice if the hardware uses one for the MOSI/MISO pins, there is a pretty valid design choice for putting the CS pin on a GPIO expander.  I have one such dev board.

With the following configuration:

```
sd_mmc_card:
  id: sd_card
  mode_1bit: true
  clk_pin: GPIO2  # CLK/SCK in SPI mode
  cmd_pin: GPIO1  # MOSI in SPI mode
  data0_pin: GPIO42  # MISO in SPI mode
  data3_pin:   # SS/CS in SPI mode
    pca9554: gpio_expander
    number: 3
```

I receive the following error when attempting to compile:
```
INFO ESPHome 2025.3.3
INFO Reading configuration config/waveshare-2.8-round.yaml...
Failed config

sd_mmc_card: [source config/2.8_round_alarm_clock_packages/sdcard.yaml:2]
  id: sd_card
  mode_1bit: True
  clk_pin: GPIO2
  cmd_pin: GPIO1
  data0_pin: GPIO42
  data3_pin: 
    
    [pca9554] is an invalid option for [data3_pin]. Please check the indentation.
    pca9554: gpio_expander
    number: 3
```
